export const profile = {
  name: "Muhammad Madni",
  role: "Full Stack Software Engineer",
  headline:
    "Building state-of-the-art systems with modern stacks and an AI-augmented workspace",
  subheading:
    "Full Stack Software Engineer specialising in business applications, automation, payment terminals, on-prem servers, and surveillance AI — using Python, Node.js, Neon, Railway, Blob storage, and AI tools for efficient delivery.",
  location: "Newton-le-Willows, St Helens, Merseyside, UK",
  locationShort: "Merseyside, UK",
  email: "madnikhan1@gmail.com",
  phone: "07799 661026",
  phoneHref: "tel:+447799661026",
  linkedin: "https://www.linkedin.com/in/madnikhan786/",
  github: "https://github.com/madnikhan",
  portfolioUrl: "https://madnikhan.dev",
  yearsExperience: 20,
  projectsDelivered: 250,
  summary:
    "Full Stack Software Engineer with over 20 years in IT and 250+ delivered projects — from websites and e-commerce to enterprise-style management systems, payment terminal integrations, local server builds, business hardware installation, networking, and surveillance AI systems. Builds with React, Next.js, TypeScript, Node.js, Python, MongoDB, Neon, Railway, and Blob storage, plus an AI-augmented workspace (ChatGPT, Anthropic Claude, Cursor AI, local AI). A software engineer who understands business problems, not just code.",
  aiWorkspace: [
    "ChatGPT",
    "Anthropic Claude",
    "Cursor AI",
    "Locally built AI systems",
  ],
  domains: [
    "Web design",
    "E-commerce",
    "Static websites",
    "Web applications",
    "Management systems",
    "Immigration casework systems",
    "Solicitor office management",
    "Government-office automation",
    "AI traffic monitoring",
    "Surveillance AI",
    "Payment terminals",
    "Local servers / on-prem",
    "Networking",
    "Hardware install",
    "Retail & POS",
    "Hospitality ops",
    "Logistics",
  ],
  marqueeItems: [
    "React",
    "Next.js",
    "TypeScript",
    "Python",
    "Node.js",
    "PostgreSQL",
    "MongoDB",
    "Neon",
    "Railway",
    "Blob storage",
    "Payment terminals",
    "Local servers",
    "Networking",
    "Surveillance AI",
    "Cursor AI",
    "Anthropic Claude",
    "ChatGPT",
    "Docker",
    "POS systems",
    "E-commerce",
    "Prisma",
    "Tailwind CSS",
  ],
  education: [
    {
      title: "Masters in Commerce (Banking & Finance)",
      detail: "Completed",
    },
    {
      title: "M.Sc Computer Science",
      detail: "Two semesters, 2010–11 — degree not completed",
    },
    {
      title: "M.Sc IBM, Coventry University",
      detail: "Postgraduate study — degree not completed",
    },
    {
      title: "CFA Level 1 Candidate",
      detail: "Professional development",
    },
  ],
} as const;

export type Profile = typeof profile;
